[[main]]
  name = "Blog"
  pageRef = "posts"
  weight = 10

[[main]]
  name = "Calculators"
  pageRef = "calculators"
  weight = 15

[[main]]
  name = "Categories"
  pageRef = "categories"
  weight = 20

[[main]]
  name = "Tags"
  pageRef = "tags"
  weight = 30

[[main]]
  name = "About"
  pageRef = "about"
  weight = 40

[[footer]]
  name = "Privacy Policy"
  url = "/privacy/"
  weight = 10

[[footer]]
  name = "Terms of Service"
  url = "/terms/"
  weight = 20

[[footer]]
  name = "Contact"
  url = "/contact/"
  weight = 30